### ISSUE TITLE
[BUG] Blocks getting harder to break with better tools 

### ISSUE THREAD

**Issue by SebyRo23** [oraxen/oraxen#550] opened 2022-11-03 18:36 UTC
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I have checked if any similar bug reports exist

### Description

It always seems that everytime you try to break an block which a better tool its seems to keep getting harder to break the block

### Steps to reproduce

Set the **minimal_type** and **best_tools** to any values and try to break a block using a netherite axe or anything better then the **minimal_type** has been set to

### Plugin Version

Oraxen version 1.145.1

### ProtocolLib Version

ProtocolLib version 4.8.0

### Server Version

This server is running Paper version git-Paper-379 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 276d830)

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by Boy0000** [comment] 2022-11-19 13:09
Unable to reproduce this, please share configs etc
Closing for now

https://user-images.githubusercontent.com/62521371/202852396-1bafebe9-c130-4b2c-89db-07e3d9532ce3.mp4

**Closed by Boy0000** 2022-11-19 13:09 UTC
Labels: bug

**Comment by Boy0000** [comment] 2022-11-19 13:12
As a sidenote minimal_type is just for the drop and best tools is the tools to use for breaking speed stuff
it then checks the tier part in your mechanics.yml
If that is out of order aka not default yes u have changed the order. But as u can see not an issue rn in default
