### ISSUE TITLE
[BUG] oraxen pack send error

### ISSUE THREAD

**Issue by Mik6060** [oraxen/oraxen#1323] opened 2024-03-31 17:51 UTC
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

I've had the problem for days that the rescore pack no longer loads and then I wanted to give myself the rescorcepack with /oraxen pack send mik6060 and then I got this error. I then went into Discord and asked what it was called and he then said I should file a bug https://mclo.gs/qJum9xO#L675

### Steps to reproduce

I don't know, I just did /oraxen pack send and then this error came https://pastebin.com/FzCyVdMZ

### Plugin Version

Oraxen version: 1.172.0!

### ProtocolLib Version

5.2.0

### Server Software & Version

This server is running Paper version git-Paper-405 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 3841722)

### How breaking is the bug?

Breaking Bug - Plugin unusable

**Comment by Boy0000** [comment] 2024-04-14 17:14
fixed in 2.0 though not able to reproduce on 1.172.0+

**Closed by Boy0000** 2024-04-14 17:14 UTC
Labels: bug
