### ISSUE TITLE
[BUG] The numbers in the scoreboard are not removed

### ISSUE THREAD

**Issue by imkyct** [oraxen/oraxen#762] opened 2023-03-22 17:14 UTC
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [x] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

Oraxen has a function that disables the numbers in the tab.

![image](https://user-images.githubusercontent.com/104898714/226982806-68d18fdd-bf49-42d3-a743-0bb14834559a.png)
It doesn't work

![image](https://user-images.githubusercontent.com/104898714/226982709-dfb692ca-56da-42ad-9726-5a7d430c9962.png)

### Steps to reproduce

1. Open file "settings.yml".
2. Find the line under the number '#182' or "hide_scoreboard_numbers: false".
3. Instead of false, make true.
4. Done! (150ms)

### Plugin Version

1.153.0

### ProtocolLib Version

4.8.0

### Server Software & Version

git-Purpur-1632 (MC: 1.18.2)

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by Boy0000** [comment] 2023-03-23 08:13
Duplicate of #755 but keeping this due to more info being provided

**Closed** 2023-04-24 09:29 UTC
Labels: bug
