### ISSUE TITLE
[SUGGESTION] Add "self-drop" option

### ISSUE THREAD

**Issue by MarkinhosMLP** [oraxen/oraxen#819] opened 2023-05-05 19:44 UTC
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

instead of

loots:
- oraxen_item: item_id
probability: 1.0

it could be

loots:
- self-drop - probability: 1.0

### Reason

with this, you wouldnt need to repeat the name a lot of times everytime you want to make a item that simply drops itself

**Comment by Boy0000** [comment] 2023-05-07 10:36
intended behaviour is same id means furniture drops its actual furniture item
this is fixed in the mentioned PR

**Closed** 2023-06-02 23:03 UTC
Labels: enhancement
