### ISSUE TITLE
[BUG] Double placing and note blocks

### ISSUE THREAD

**Issue by SlicedWatermelon** [oraxen/oraxen#911] opened 2023-06-23 10:04 UTC
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

After updating server to 1.20.1 and Oraxen to latest version when placing furniture it auto places 2 of them, also sometimes note block appearrs instead of furniture when placing it

### Steps to reproduce

placing furniture auto places 2nd of them,  note block appearrs instead of furniture when placing it

### Plugin Version

1.157.1

### ProtocolLib Version

5.1.0-Snapshot 652

### Server Software & Version

 This server is running Paper version git-Paper-45 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: b169678)

### How breaking is the bug?

Breaking Bug - Plugin unusable

**Comment by SlicedWatermelon** [comment] 2023-06-23 10:06
Uploading CCropsproblem-1.mp4…

**Comment by SlicedWatermelon** [comment] 2023-06-23 10:06
https://github.com/oraxen/oraxen/assets/111089420/a72826f6-5227-40e4-ac6f-0e2af05c1596

**Comment by Boy0000** [comment] 2023-06-23 11:25
duplicate of #910 please refer to that issue

**Closed by Boy0000** 2023-06-23 11:25 UTC
Labels: bug
