### ISSUE TITLE
[BUG] Sounds not being replaced

### ISSUE THREAD

**Issue by minustenchan** [oraxen/oraxen#1445] opened 2024-06-30 21:54 UTC
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

in a fresh install of 2.0 Oraxen in 1.20.6 paper latest build, when placing/breaking mining custom noteblocks i can still hear the wood sound

### Steps to reproduce

place/break/mine custom noteblock, u will hear the wood sound alongside the sound that u set the custom noteblock to

### Plugin Version

2.0-SNAPSHOT

### ProtocolLib Version

5.3.0-SNAPSHOT-723

### Server Software & Version

1.20.6-147-ver/1.20.6@e41d44f

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by Boy0000** [comment] 2024-07-02 08:30
yeah the issue is with the new RP library, ive opened a PR just waiting for it to be merged in

**Comment by Boy0000** [comment] 2024-07-03 12:36
should also be patched now 👍

**Closed by Boy0000** 2024-07-03 12:36 UTC
Labels: bug
