### ISSUE TITLE
[BUG]  After reconnecting to the server, some textures stop working, using one texture

### ISSUE THREAD

**Issue by NeotenySS** [oraxen/oraxen#551] opened 2022-11-05 08:10 UTC
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I have checked if any similar bug reports exist

### Description

Some textures just stopped working, but most of the textures that are used for items have no problem.
Textures are only partially broken in some menus.
This error appears only on hosting (dedicated server).
I tried to reproduce the error on a test server on my pc, windows 10, but there were no problems.
I also report that the test server and the server on the hosting has exactly the same settings.
I made a detailed example video for you:
https://youtu.be/75BoRpBELDg

### Steps to reproduce

1. Started the server on the hosting site (Debian GNU/Linux 11 (bullseye))
2. Connected to the server.
3. Checked the textures, they work.
4. Leaving the server.
5. Went back on the server.
Result: some textures are no longer working

### Plugin Version

  [Sat 11:07:48 INFO ] Oraxen version 1.145.1
  [Sat 11:07:48 INFO ] Author: Th0rgal

### ProtocolLib Version

[Sat 11:08:08 INFO ] ProtocolLib version 5.0.0-SNAPSHOT-b586
  [Sat 11:08:08 INFO ] Provides read/write access to the Minecraft protocol.
  [Sat 11:08:08 INFO ] Authors: dmulloy2 and comphenix

### Server Version

  [Sat 11:08:21 INFO ] This server is running CraftBukkit version 3599-Spigot (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT)

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by Boy0000** [comment] 2022-11-05 08:15
This is probably not an oraxen issue
The pack is generated when server starts then sent
IDK why it would be different if you just

1.  start server
2. join and get working pack
3. leave
4. rejoin and broken pack
with **absolutely nothing else** in between

If you join, then reloaded the plugin then that could be why @NeotenySS

**Comment by NeotenySS** [comment] 2022-11-05 10:17
What makes you think I reloaded the plugin?
I just turned on the server and then shown in the video.
I logged into the server, installed the resource package, then I just logged out of the server and reconnected to it.
I did not restart the plugin, did not change the file settings or other plugin files. The video has all the information that shows all the error, just reconnected to the server and everything. @Boy0000

**Comment by Boy0000** [comment] 2022-11-05 10:19
![image](https://user-images.githubusercontent.com/62521371/200114989-eb9c453c-9ece-43dc-b1eb-0725d18931ef.png)
the video shows this which is only sent when you use the oraxen reload commands. Thats why i asked if you reloaded... @NeotenySS

**Comment by NeotenySS** [comment] 2022-11-05 10:28
Ah...
I downloaded all the plugin files from the test server to the server hosting, and since the version can not use /o reload all.
I used /o reload pack to restore the resource pack to a working state and then started the video which demonstrates this error.
@Boy0000

**Comment by Boy0000** [comment] 2022-11-05 10:29
Restart your server fully and do it without reloading anything at all
I am unable to reproduce this myself so I am unable to fix it

**Comment by NeotenySS** [comment] 2022-11-05 10:30
The only way to fix this problem is to reload all the files from the "pack" folder into the plugin folder and then type /o reload pack

**Comment by Boy0000** [comment] 2022-11-05 10:32
no clue what you are talking about...
This issue is caused because ur reloading. There should be 0 need to reload absolutely anything at all
When the server starts the pack is created. When you leave the pack is unsent to the player, and when join it is resent
The pack doesnt change at all.

If you reload it will regenerate the pack and perhaps not resend it to all players. Dont reload and try, otherwise i  will close this issue as unable to reproduce and not able to fix. Since this seems to be only happening to you I will assume the issue isnt with Oraxen itself

**Comment by NeotenySS** [comment] 2022-11-05 10:36
Wait for the video

**Comment by NeotenySS** [comment] 2022-11-05 10:42
https://youtu.be/s1ORlPANGUw   @Boy0000 
Just start host server and test server.
No reload plugins or pack and ect.

**Comment by Boy0000** [comment] 2022-11-05 10:44
You showed me you joining 2 different servers
Are you sure all the configs are literally 100% identical?
Delete the non working servers plugins/Oraxen folder and copy the working one over

**Comment by NeotenySS** [comment] 2022-11-05 10:57
![image](https://user-images.githubusercontent.com/11386982/200116472-0ef6da94-25f6-48a0-9f46-87767063c7e4.png)

Or do you want me to delete the folder completely and the plugin generate all the files from scratch?

Since I just copied the test server files and uploaded them to the hosting, with the same settings and ect

**Comment by NeotenySS** [comment] 2022-11-05 10:58
100% copied from the test server to the hosting server.

The strange thing is that the rest of the textures, as you can see, work, the inventory works, the objects work

**Comment by Boy0000** [comment] 2022-11-05 11:00
No clue, this doesnt seem like oraxens fault and moreso an issue on your end. Further this has turned into support and not a bugreport so closing this. Use discord for support

**Closed** 2022-11-05 11:00 UTC
Labels: bug
