### ISSUE TITLE
[BUG] i have the plugin Lands when I place blocks in chunks that are claim I get errors

### ISSUE THREAD

**Issue by FrozzenRod** [oraxen/oraxen#943] opened 2023-07-06 12:30 UTC
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

i have the plugin Lands when I place blocks in chunks that are claim i got a error in the console.

### Steps to reproduce

install the lands plugin: https://www.spigotmc.org/resources/lands-%E2%AD%95-land-claim-plugin-%E2%9C%85-grief-prevention-protection-gui-management-nations-wars-1-20-support.53313/updates

install latest version of Oraxen

claim a chunk and a block must be placed in this chunk

### Plugin Version

![image](https://github.com/oraxen/oraxen/assets/73665630/2585a340-4418-406c-a95e-cc14ed1c3fcd)

### ProtocolLib Version

![image](https://github.com/oraxen/oraxen/assets/73665630/c70513f8-c780-4ff9-9e48-34bfcdf7aa31)

### Server Software & Version

![image](https://github.com/oraxen/oraxen/assets/73665630/e65f9158-a505-4b45-8342-519b2178db93)

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by FrozzenRod** [comment] 2023-07-06 12:39
I've just tried it with a double account and it's not a permission problem.

**Comment by FrozzenRod** [comment] 2023-07-06 12:40
`error:
[14:38:27 ERROR]: Could not pass event PlayerInteractEvent to Oraxen v1.157.3
java.lang.LinkageError: loader constraint violation: loader 'oraxen-1.157.3.jar' @3311d4 wants to load interface me.angeschossen.lands.api.land.Area. A different interface with the same name was previously loaded by 'Lands-6.32.4.jar' @23818c7f. (me.angeschossen.lands.api.land.Area is in unnamed module of loader 'Lands-6.32.4.jar' @23818c7f, parent loader java.net.URLClassLoader @421faab1)
        at io.th0rgal.protectionlib.compatibilities.LandsCompat.getLand(LandsCompat.java:67) ~[oraxen-1.157.3.jar:?]
        at io.th0rgal.protectionlib.compatibilities.LandsCompat.canUse(LandsCompat.java:60) ~[oraxen-1.157.3.jar:?]
        at io.th0rgal.protectionlib.ProtectionLib.lambda$canUse$9(ProtectionLib.java:40) ~[oraxen-1.157.3.jar:?]
        at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90) ~[?:?]
        at java.util.HashMap$KeySpliterator.tryAdvance(HashMap.java:1728) ~[?:?]
        at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) ~[?:?]
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230) ~[?:?]
        at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.allMatch(ReferencePipeline.java:637) ~[?:?]
        at io.th0rgal.protectionlib.ProtectionLib.canUse(ProtectionLib.java:40) ~[oraxen-1.157.3.jar:?]
        at io.th0rgal.oraxen.mechanics.provided.combat.spell.energyblast.EnergyBlastMechanicManager.onPlayerUse(EnergyBlastMechanicManager.java:48) ~[oraxen-1.157.3.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor545.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:git-Paper-58]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.1.jar:git-Paper-58]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.1.jar:git-Paper-58]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:561) ~[paper-1.20.1.jar:git-Paper-58]
        at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:537) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1960) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:37) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.a(ServerboundUseItemOnPacket.java:9) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.1.jar:git-Paper-58]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1339) ~[paper-1.20.1.jar:git-Paper-58]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.20.1.jar:git-Paper-58]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1316) ~[paper-1.20.1.jar:git-Paper-58]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1309) ~[paper-1.20.1.jar:git-Paper-58]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1287) ~[paper-1.20.1.jar:git-Paper-58]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1175) ~[paper-1.20.1.jar:git-Paper-58]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-58]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
`

**Comment by Boy0000** [comment] 2023-07-09 09:28
@FrozzenRod entirely unable to reproduce this on my end, and others that use Lands dont have this issue aswell
According to their dev this might happen if you reload the plugin with plugman or something similar
Closing this for now

**Closed by Boy0000** 2023-07-09 09:28 UTC
Labels: bug
