### ISSUE TITLE
[BUG] Duplication of 3d models upon placement

### ISSUE THREAD

**Issue by questionaccount1** [oraxen/oraxen#910] opened 2023-06-22 18:32 UTC
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

Furniture models duplicate when being placed if it has the mechanic "limited_placing". Also limited_placing doesnt work anymore in general. I can place objects on the floor even though thats not enabled in the limited_placing mechanic (its suppose to only be placed on a wall, yet I now can place it on ceiling and floor)

### Steps to reproduce

Use a furniture with the mechanic limited_placing
Place it on the wall/ceiling and there will be two furnitures placed instead of one.

### Plugin Version

1.157.1

### ProtocolLib Version

ProtocolLib 5.0.0

### Server Software & Version

git-Paper-45 (MC: 1.20.1)

### How breaking is the bug?

Breaking Bug - Plugin unusable

**Comment by Boy0000** [comment] 2023-06-22 22:14
it is always helpful if you provide a concrete config example here
Speeds it up and clears things up alot @questionaccount1 
can do it without now but in general

**Comment by Boy0000** [comment] 2023-06-22 22:16
also please record this and show it, im entirely unable to replicate any of this

**Comment by questionaccount1** [comment] 2023-06-22 23:24
![91bb9afe5795279c20a1cba9a77607b4](https://github.com/oraxen/oraxen/assets/81465695/761f69f3-f24d-4892-9a10-765eb8b28b15)
Here is a gif above with the example, I place a normal block as an example to show that it doesn't occur with anything other than furniture. 

And here is the configuration of the example furniture used in the gif. This effect can also be replicated on furniture with 'limited_placing' mechanic for floor too, by placing the object against the wall

And here is the configuration of the example furniture used in the gif. 

redoakpaint:
  displayname: <gray>Framed Oak Painting
  material: PAPER
  Mechanics:
    furniture:
      type: DISPLAY_ENTITY
      hitbox:
        width: 0.4
        height: 0.3
      display_entity_properties:
        display_transform: FIXED
        view_range: 64
      limited_placing:
        roof: false
        floor: false
        wall: true
      barrier: true
      drop: # useless if you are not using a barrier
        silktouch: false
        loots:
        - oraxen_item: redoakpaint
          probability: 1.0
      block_sounds:
        place_sound: block.stone.place
        break_sound: block.stone.break
        hit_sound: block.stone.hit
        step:
          sound: block.stone.step
          volume: 0.25
        fall:
          sound: block.stone.fall
          volume: 0.25
  Pack:
    generate_model: false
    model: redvibe/redoakpaint
    custom_model_data: 121345

This effect can also be replicated on furniture with 'limited_placing' mechanic for floor too, by placing the object against the wall example gif and config of furniture: 
![ec30693fa9f9595de4744ee1ccb3de3e](https://github.com/oraxen/oraxen/assets/81465695/b29dce9d-2042-4345-a3ea-d9475f2f990b)


basket_apple:
  displayname: <gray>Basket of Apples
  material: PAPER
  Mechanics:
    furniture:
      type: DISPLAY_ENTITY
      hitbox:
        width: 0.4
        height: 0.3
      display_entity_properties:
        display_transform: FIXED
        view_range: 64
      limited_placing:
        roof: false
        floor: true
        wall: false
      barrier: true
      drop: # useless if you are not using a barrier
        silktouch: false
        loots:
        - oraxen_item: basket_apple
          probability: 1.0
      block_sounds:
        place_sound: block.stone.place
        break_sound: block.stone.break
        hit_sound: block.stone.hit
        step:
          sound: block.stone.step
          volume: 0.25
        fall:
          sound: block.stone.fall
          volume: 0.25
  Pack:
    generate_model: false
    model: furniture/basket_apple
    custom_model_data: 312556

Thank you very much

**Comment by SlicedWatermelon** [comment] 2023-06-23 10:05
Same problem here

**Comment by Boy0000** [comment] 2023-06-23 10:51
for future @questionaccount1 please use codeblocks
that config u provided is ofv malformed now

![image](https://github.com/oraxen/oraxen/assets/62521371/2ae7b5e7-96e1-4608-ad49-eb306998f495)
just a tip to make it actually usable 👍

**Comment by Boy0000** [comment] 2023-06-23 11:24
https://github.com/oraxen/oraxen/assets/62521371/270fa7f4-8a7e-4bf0-a5d9-8cbde61c99c5

unable to reproduce this with the configs provided on 1.19.2 and all the way up to 1.20
please try this on a server with **just oraxen and protocollib 5.0**
if it still happens im not sure, but yeah entirely unable to reproduce this issue rn @questionaccount1 @SlicedWatermelon

**Comment by SlicedWatermelon** [comment] 2023-06-23 12:44
1.20.1 .....

**Comment by questionaccount1** [comment] 2023-06-23 14:04
Can confirm that it is still happening on a server running **only** Oraxen and ProtocolLib (latest versions for both)

**Comment by Boy0000** [comment] 2023-06-23 14:37
https://github.com/PaperMC/Paper/issues/9356#issuecomment-1595418767

Seems to be a Paper bug, hence why it only happens in 1.20.1
Ive been able to reproduce it now but yeah seems this isnt an oraxen bug

**Comment by Boy0000** [comment] 2023-06-23 15:13
you can track the fix here: https://github.com/PaperMC/Paper/issues/9356#issuecomment-1604423195

for now the fix is to revert to build 37 of paper here: https://papermc.io/downloads/all

**Comment by questionaccount1** [comment] 2023-06-23 15:35
Build #37 seems to have fixed the duplication issue, however the limited_placing issue still persists as I am able to place something that should only be able to be placed on walls, on floors and ceilings.

**Comment by Boy0000** [comment] 2023-06-23 15:50
please split that into a separate issue, prefer to have them not mixed as makes it harder to track actual bugs 👍 
ill close this whenever the double placing is fixed so

**Comment by Boy0000** [comment] 2023-06-23 16:22
fixed as of latest paper build

**Closed by Boy0000** 2023-06-23 16:22 UTC
Labels: bug
