### ISSUE TITLE
[BUG] Missing sounds (1.20.1)

### ISSUE THREAD

**Issue by KlausTrophobie** [oraxen/oraxen#928] opened 2023-06-28 11:44 UTC
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

Unfortunately, some sounds are currently missing when using the resource pack. We could fix the missing WOOD sounds by deactivating the custom sounds in the mechanic.yml. Currently, however, the STONE sounds are also missing and we can't find a way to enable them again.

### Steps to reproduce

You just have to play on 1.20.1 and use 1.20.1 (Paper) as the server version while you have the resource pack activated. Then try to trigger the corresponding sounds (step, hit, break).

### Plugin Version

1.157.2

### ProtocolLib Version

5.1.0-SNAPSHOT-653

### Server Software & Version

1.20.1 Paper

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by Boy0000** [comment] 2023-06-28 11:55
Mechanics.yml should include options to restore both WOOD and STONE
![image](https://github.com/oraxen/oraxen/assets/62521371/09ef3bf1-6e0e-45af-915d-a9b169177423)

This shouldnt be needed however unless something changed in 1.20.1, which I will look into

**Comment by KlausTrophobie** [comment] 2023-06-28 12:08
both are set to "false" atm

**Comment by Boy0000** [comment] 2023-06-28 13:04
this is me on an unmodded client with everything default oraxen and latest 1.20.1 build of paper
I am not able to reproduce this issue. Can you check, when both settings are enabled, the sounds.json in the final pack.zip in Oraxen/pack? might need to disable Pack.protection in settings.yml to open it

https://github.com/oraxen/oraxen/assets/62521371/63e60913-f6c8-4f6b-b8c7-89929fda692f

**Comment by Boy0000** [comment] 2023-06-28 13:21
found the issue with disabling the sounds, will be fixed in 1.157.3

**Comment by KlausTrophobie** [comment] 2023-06-28 13:30
Yes you are right, if both are set to "true", the WOOD sound is missing. If both are set to false, the WOOD sound is present again, but the STONE sound is missing.

just FYI sounds.json with both enabled:
`{"welcome":{"category":"master","sounds":["welcome"]},"block.wood.step":{"category":"master","replace":true,"sounds":[]},"block.wood.place":{"category":"master","replace":true,"sounds":[]},"block.wood.break":{"category":"master","replace":true,"sounds":[]},"block.wood.fall":{"category":"master","replace":true,"sounds":[]},"block.wood.hit":{"category":"master","replace":true,"sounds":[]},"required.wood.hit":{"category":"master","subtitle":"subtitles.block.generic.hit","sounds":["step/wood1","step/wood2","step/wood3","step/wood4","step/wood5","step/wood6"]},"required.wood.place":{"category":"master","subtitle":"subtitles.block.generic.place","sounds":["dig/wood1","dig/wood2","dig/wood3","dig/wood4"]},"required.wood.break":{"category":"master","subtitle":"subtitles.block.generic.break","sounds":["dig/wood1","dig/wood2","dig/wood3","dig/wood4"]},"required.wood.step":{"category":"master","subtitle":"subtitles.block.generic.footsteps","sounds":["step/wood1","step/wood2","step/wood3","step/wood4","step/wood5","step/wood6"]},"required.wood.fall":{"category":"master","sounds":["step/wood1","step/wood2","step/wood3","step/wood4","step/wood5","step/wood6"]}}`


Thanks for fixing :)

**Closed** 2023-06-29 09:02 UTC
Labels: bug
