### ISSUE TITLE
[Bug] bigmining mechanic bugs

### ISSUE THREAD

**Issue by BookWyrm114** [oraxen/oraxen#254] opened 2021-11-11 17:13 UTC
the bigmining mechanic won't work while the player is in water, and it occasionally causes custom blocks to drop noteblocks

**Comment by Boy0000** [comment] 2022-10-31 14:25
Unable to reproduce this so closing, if it is still an issue I will reopen and fix this

**Closed by Boy0000** 2022-10-31 14:25 UTC
