### ISSUE TITLE
[BUG] Lever or button turns custom blocks into noteblocks

### ISSUE THREAD

**Issue by MrNolex** [oraxen/oraxen#462] opened 2022-08-30 15:38 UTC
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I have checked if any similar bug reports exist

### Description

https://media.discordapp.net/attachments/613680450761785344/1014185823966597200/unknown.png?width=709&height=676

### Steps to reproduce

Everything on rthe image

### Plugin Version

latest

### ProtocolLib Version

latest

### Server Version

1.19

### How breaking is the bug?

Breaking Bug - Plugin unusable

**Comment by Boy0000** [comment] 2022-08-30 17:56
duplicate of #458

**Closed by Boy0000** 2022-08-30 17:56 UTC
Labels: bug
