### ISSUE TITLE
[BUG] Esc Menu not working anymore

### ISSUE THREAD

**Issue by KlausTrophobie** [oraxen/oraxen#865] opened 2023-06-07 11:33 UTC
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

Since 1.156.3/.4 update, the Escape Menu no longer works. Do I have to change anything special to make it work again? (only using global.json)

After reverting back to version 1.156.2 everything works again as desired. 

![qCsIwI3](https://github.com/oraxen/oraxen/assets/25036374/5d1a878d-3ccf-4c02-89a6-89741ad14ccc)
![uuhIC7x](https://github.com/oraxen/oraxen/assets/25036374/056cf878-b7d1-4bd3-b544-f901234d4aed)
![aHuasEv](https://github.com/oraxen/oraxen/assets/25036374/ed892464-0774-43f3-b8a3-59638ef421df)

### Steps to reproduce

Just updating to 1.156.3/.4 and using default global.json

### Plugin Version

Oraxen version 1.156.4

### ProtocolLib Version

5.0.0

### Server Software & Version

Paper 1.19.4

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by Boy0000** [comment] 2023-06-07 21:52
duplicate of #862 , fixed in #840

**Closed by Boy0000** 2023-06-07 21:52 UTC
Labels: bug
