### ISSUE TITLE
isn't uploading to the server

### ISSUE THREAD

**Issue by Darkness098123** [oraxen/oraxen#227] opened 2021-09-14 03:54 UTC
[22:47:10 ERROR]: [null] [Oraxen] The resource pack has not been uploaded to the server. Usually this is due to an excessive size.
[22:47:10 INFO]: oraxen | Resourcepack not uploaded

**Comment by Th0rgal** [comment] 2021-09-17 14:49
hey, this issue was caused by the domain not resolving, it's now fixed

**Closed by Th0rgal** 2021-09-17 14:49 UTC
