### ISSUE TITLE
[PLACING] <Value Shift>

### ISSUE THREAD

**Issue by Mariosonicman91** [oraxen/oraxen#1170] opened 2023-12-28 04:19 UTC
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

When placing down a (Default) custom block onto a Vanilla Block, it works fine, but when placing a custom block against ANOTHER custom block, it's value seems to shift through the other custom blocks until it reaches the note block. Plus, sneaking cancels the placing animation. This seems like a HUGE issue. I'm running my server on 1.20.1, what's going on?

### Steps to reproduce

1. Open the Oraxen inventory
2. Grab a default block (preferably an ore)
3. Place it down
4. Place another one against it
5. You will see the first block's value seems to shift, and becomes a different bloc

### Plugin Version

1.166.0

### ProtocolLib Version

5.10

### Server Software & Version

1.20.1

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by Boy0000** [comment] 2023-12-28 21:41
unable to reproduce this on latest devbuild
cant reproduce it on spigot release either
feel free to try the devbuilds in discord
either way seems to be fixed in #1065

**Closed by Boy0000** 2023-12-28 21:41 UTC
Labels: bug
