### ISSUE TITLE
[SUGGESTION] Improve custom armor

### ISSUE THREAD

**Issue by lucian929** [oraxen/oraxen#341] opened 2022-05-08 23:38 UTC
Let's be honest - the custom armor mechanic sucks. It's poorly documented, doesn't work well, and just overall needs work.

I haven't studied it enough to write documentation and fully write what needs changes, so I'm going to create this issue and edit it as I go. I just wanted to start writing it so I don't forget later.

## 1 - CIT Compatiability

There should be an added option to generate the necessary CIT files so Oraxen armor works with shaders. This is pretty simple to do, see https://docs.oraxen.com/configuration/custom-armors/shader-armors

## 2 - Generation

When creating your armor set, the wiki does not specify to add a pixel to your image so it works correctly with the shader. I'm not sure if oraxen is supposed to generate the pixel itself, but if it is supposed to, that does not work correctly.

MORE COMING SOON:tm:

**Comment by Bugin4** [comment] 2022-07-25 07:22
Hi, could you please post an image with working armor texture which contains the pixel you mentioned?

**Comment by Boy0000** [comment] 2022-08-17 19:51
Closing as this works as intended. Future release will have proper example for CIT Compatibility shipped with for the 3 default sets.
As for documentation, I will redo all of it shortly

**Closed by Boy0000** 2022-08-17 19:51 UTC
