### ISSUE TITLE
[BUG] durability doesn't go down when mining custom blocks

### ISSUE THREAD

**Issue by magicelk235** [oraxen/oraxen#917] opened 2023-06-24 14:57 UTC
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

durability doesn't go down when mining custom blocks

### Steps to reproduce

place a block then break it

### Plugin Version

1.157.1

### ProtocolLib Version

5.1.0-SNAPSHOT-644

### Server Software & Version

Paper version git-Paper-307 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 476ef25)

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by Boy0000** [comment] 2023-06-24 16:24
duplicate of #708

**Closed by Boy0000** 2023-06-24 16:24 UTC
Labels: bug
