### ISSUE TITLE
[BUG] <error when breaking a block>

### ISSUE THREAD

**Issue by MonG3n** [oraxen/oraxen#1400] opened 2024-05-25 15:56 UTC
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [ ] I have checked if any similar bug reports exist

### Description

When I try to knock out an oraxen custom block, the console keeps sending warnings and won't let me knock out the object, only in creative mode.

### Steps to reproduce

When I click on an oraxen custom block it sends a warning. If I start hitting a custom oraxen block it will spam without stopping.

### Plugin Version

[17:54:26 INFO]: Oraxen version 1.175.0

### ProtocolLib Version

ProtocolLib version 5.2.1-SNAPSHOT-689

### Server Software & Version

[17:55:23 INFO]: Current: git-Purpur-2176 (MC: 1.20.4)*

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by MonG3n** [comment] 2024-05-25 15:57
https://mclo.gs/BLqEe02

**Comment by Boy0000** [comment] 2024-05-26 12:27
unable to reproduce this on Paper 1.20.4
try using a Paper server and see

This bug was fixed in 1.175.0 from  1.174.0 so not sure @MonG3n

**Comment by MonG3n** [comment] 2024-05-27 10:05
I managed to produce it again! Is it possible that it's just my item's configuration that's wrong?
dry_pot:
  displayname: <white>Pot
  material: SUGAR
  Pack:
    generate_model: false
    model: item/basics/dry_pot
    custom_model_data: 1000
  Mechanics:
    noteblock:
      custom_variation: 51
      model: item/basics/dry_pot
      hardness: 5
      block_sounds:
        place_sound: block.bamboo_wood.place
        break_sound: block.bamboo_wood.break
      drop:
        silktouch: false
        loots:
        - oraxen_item: dry_pot
          probability: 1.0

**Comment by Boy0000** [comment] 2024-05-27 10:32
@MonG3n as mentioned please use codeblocks or take a screenshot, ur config isnt readable here

As mentioned please ensure that this is on 1.175.0 and use a **Paper** not Purpur server and see

**Comment by MonG3n** [comment] 2024-05-27 10:37
![image](https://github.com/oraxen/oraxen/assets/129215940/b3d1a875-5fb7-4fc0-af5a-423de817e54e)
![image](https://github.com/oraxen/oraxen/assets/129215940/84a501ea-299a-4d84-b1a4-552e2c0e85a4)

**Comment by MonG3n** [comment] 2024-05-31 14:27
I mess something up, is that why it's not good for me? Or what is the reason?

**Comment by Boy0000** [comment] 2024-05-31 19:51
@MonG3n i am not sure i cannot replicate this
please record a clip of how to reproduce this and ill look again

**Comment by MonG3n** [comment] 2024-06-01 22:59
https://youtu.be/oBE431jcPX4

**Comment by Boy0000** [comment] 2024-06-02 11:18
yeah sadly i am out of ideas
I am testing this on a 1.20.4 server and have 0 such issues
Neither does the error make sense either

not too sure how to further approach this sadly

**Closed** 2024-06-05 16:38 UTC
Labels: bug
