### ISSUE TITLE
[BUG] <name for bug>

### ISSUE THREAD

**Issue by scarfits** [oraxen/oraxen#868] opened 2023-06-08 12:31 UTC
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

Any item im using a custom model/texture for us appearing perfect when im holding it but when it comes to me throwing it on the ground it appears as the material set and not the custom texture. So if i threw a key in which i have a custom texture for it would appear normal in my hand and then as paper when thrown on the group.

### Steps to reproduce

Get an item with a custom texture//model, throw it on the ground & and it appears as the set material.

### Plugin Version

Plugin version is 1.156.4

### ProtocolLib Version

Latest

### Server Software & Version

Server version is 1.19.4

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by Boy0000** [comment] 2023-06-10 19:50
duplicate of already opened issue which is marked as fixed for next update

**Closed by Boy0000** 2023-06-10 19:50 UTC
Labels: bug
