### ISSUE TITLE
Plugin Oraxen v1.150.2 generated an exception while executing task 6

### ISSUE THREAD

**Issue by FireQuacker** [oraxen/oraxen#648] opened 2023-01-19 20:53 UTC
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

![image](https://user-images.githubusercontent.com/58408434/213556825-eab338ae-d8cc-4a6c-99f6-ac682ae51420.png)

resource pack wont load

### Steps to reproduce

Install Oraxen on Pupur 1.19 server

### Plugin Version

1.150.2

### ProtocolLib Version

Build 612

### Server Software & Version

[20:51:57 INFO]: Checking version, please wait...
[20:51:58 INFO]: Current: git-Purpur-1735 (MC: 1.19)*
* You are running the latest version

### How breaking is the bug?

Breaking Bug - Plugin unusable

**Comment by Boy0000** [comment] 2023-01-20 11:21
Was caused by issue with polymath server, this should be fixed now

**Closed by Boy0000** 2023-01-20 11:21 UTC
Labels: bug
